# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      # install server dependencies
      - cd app
      - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      - npm install 
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls -la
artifacts:
  files:
    - '**/*' 